swiftmailer:
    #url: '%env(MAILER_URL)%'
    #transport: %env(mailer_transport)%
    #host:      %env(mailer_host)%
    #port:      %env(mailer_port)%
    #encryption: %env(mailer_encryption)%
    #username:  %env(mailer_user)%
    #password:  %env(mailer_password)%
    
web_profiler:
    intercept_redirects: true
        
